name: Soni Wijaya
markdown: kramdown
highlighter: rouge
github: https://www.github.com/soniwijaya
about:  Hi, I'm Soni. I want to develop my career and expertise in Information Technology, specifically in Website Development. Having an in-middle knowledge including advanced Javascript ( React.js ).
urls:
    - text: Twitter
      url: https://twitter.com/soniwijaya
    - text: Github
      url: https://github.com/soniwijaya
baseurl: ''
future: true